
drop table if exists peticiones;

create table peticiones(
        idusuario  integer generated by default as identity,
        fecha      varchar,
		api		   varchar,
        request    varchar,
        response   varchar, 
		primary key (idusuario)

);